### ISSUE TITLE
Problems with chrome 

### ISSUE THREAD

**Issue by mveccia** [nbrosowsky/tonejs-instruments#13]
I downloaded the project under my own domain, but I get the following message:
"I'm sorry, there has been an error loading the samples. This demo works best on on the most up-to-date version of Chrome."
currently the chrome version is 88.0.4324.104 (official build) (64-bit)
While your demo works perfectly.
Maybe you need to install some extension?

**Comment by mveccia** [comment]
fixed: in the code the samples are in the directory "/tonejs-instruments/samples/" while the samples were in the directory "/samples/"...

**Comment by nbrosowsky** [comment]
Fixed, thanks!
