### ISSUE TITLE
Recommend adding Tone.Buffer.on('load', fn(){}) to your readme/sample

### ISSUE THREAD

**Issue by autemox** [nbrosowsky/tonejs-instruments#4]
For the readme, I recommend adding Tone.Buffer.on('load', function() { });.  That way people finding this project for the first time can quickly get started instead of investigating buffering problems.

e.g.

>        // passing an array of instrument names will load all the instruments listed returning a new object, 
>        // each property a tone.js object
>            var instruments = SampleLibrary.load({
>            instruments: ["piano","harmonium","violin"]
>        });
>
>        // waits for instrument sound files to load from /samples/
>        Tone.Buffer.on('load', function() {
>          // play instrument sound
>          instruments['piano'].toMaster();
>          instruments['piano'].triggerAttack("A3")'
>        });

**Comment by nbrosowsky** [comment]
Thanks for the suggestion! Added.
