### ISSUE TITLE
Massive distortion when triggering attack on multiple notes.

### ISSUE THREAD

**Issue by sustained** [nbrosowsky/tonejs-instruments#7]
The issue is in the title.

# Reproduction

Basically follow the README then change the `triggerAttack` to e.g.:

```js
instruments.piano.triggerAttack(["A2", "C3", "E3"]);
```

------

Any idea what the problem could be?

# UPDATE

It seems that this problem only occurs the first time. So if I do a `setInterval` (just as a quick example/test, I completely forgot how to work with Tone!) then the first chord will be massively distorted and the rest won't be so bad.

**Comment by nbrosowsky** [comment]
I can't recreate this issue, but let me know if it persists.
